import "../../public/styles/index.scss";

import { CssBaseline } from "@mui/material";
import { Footer } from "@/components/Footer/Footer";
import { Header } from "@/components/Header/Header";
import { Loading } from "@/components/Loading/Loading";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import PageTransition from "@/components/Loading/PageTransition";
import { Suspense } from "react";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bolero - Online Ticket Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
